# Generated by Django 4.2.4 on 2023-09-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScanResult',
            new_name='FileScanResult',
        ),
    ]
