# Generated by Django 4.2.4 on 2023-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_scanresult_filescanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('port_ranges', models.CharField(max_length=255)),
                ('open_ports', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ZapScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('target_url', models.URLField()),
                ('scan_results', models.JSONField()),
            ],
        ),
    ]
