# Generated by Django 4.2.4 on 2023-10-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_scanresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
